Added electric field sensor driver
VIP-LES/EosPayload pull request #90
Opened 2023-10-24 15:35 UTC by eaeyal

2023-11-16 22:48 UTC, DarylDohner requested changes
see comments

2023-11-16 22:48 UTC, DarylDohner commented on config.json
> +      "device_id": "MISC_3",
should be MISC_SENSOR_3

2023-11-16 22:48 UTC, DarylDohner commented on config.json
> +      "name": "electric_field_sensor",
use hyphens not underscores

2023-11-16 22:48 UTC, DarylDohner commented on EosPayload/drivers/efield_driver.py
> +                voltages = [ADC.read(pin) for pin in adc_pins]
you should restructure this into a loop so you can read the pins independently.  that way if an exception is raised on reading pin1, we can still try to read pins 2 and 3

2023-11-16 22:48 UTC, DarylDohner commented on EosPayload/drivers/efield_driver.py
> +            self._mqtt.send(Topic.RADIO_TRANSMIT, packet)
include this stuff in your try / catch as well

2023-11-16 22:48 UTC, DarylDohner commented on EosPayload/drivers/efield_driver.py
> +            self.thread_sleep(logger, 2)
do you want to read data and transmit data at the same rate?  How rapidly are the values expected to change for this sensor?  If it changes more rapidly, you may want to read and data_log every 1s or 0.5s.  How valuable is a real-time measurement at the ground station?  If its something that could suddenly spike, maybe we want to transmit every 1s.  if it's something that is going to be relatively stable, then maybe we dont need so many points on the live graph and you transmit every 5s.  Maybe log+transmit every 2s is what works for this.  Just something for you to think about

2023-11-17 01:41 UTC, DarylDohner submitted a review, later dismissed

2023-11-17 01:41 UTC, DarylDohner commented on EosPayload/drivers/efield_driver.py
> +                    self.thread_sleep(logger, 1)
this thread sleep needs to happen outside this if block, otherwise you are only sleeping on transmit

2023-11-17 18:33 UTC, David-Rey approved these changes
lgtm

2023-11-17 18:34 UTC, merged