#93 mechanical valve driver
VIP-LES/EosPayload pull request #94
Opened 2023-11-03 16:49 UTC by thejoelm

2023-11-03 16:55 UTC, IonLi09 submitted a review, later dismissed
lgtm

2023-11-07 17:34 UTC, panyab commented
Software hasn't implemented a command for manual valve opening, so that shouldn't be there. Also, you need to register VALVE_COMMAND in the EosLib/lib/mqtt/init.py file.

2023-11-07 21:51 UTC, DarylDohner requested changes
incomplete, hasnt been tested, see panya's comment &
https://vip-les.slack.com/archives/C05RS9BJKPA/p1699388426129139
btw you need a config.json entry for this driver

2023-11-10 20:50 UTC, aryanbattula reviewed
lgtm

2023-11-10 20:56 UTC, DarylDohner requested changes

2023-11-10 20:56 UTC, DarylDohner commented on valve_driver.py
> +        user_data['queue'].put(1)
this seems unintentional, probably want to remove this since the actual enqueing is done below

2023-11-14 21:53 UTC, aryanbattula approved these changes
lgtm!

2023-11-14 21:54 UTC, merged