updated cutdown driver with cutdown format
VIP-LES/EosPayload pull request #96
Opened 2023-11-03 20:17 UTC by IonLi09

added cutdown sequence number to logger.

2023-11-03 20:30 UTC, DarylDohner submitted a review, later dismissed
a few things
1. see comments
2. you need to actually test this, i would recommend either writing a quick script that sends a cutdown command over mqtt or just hooking up the radio / ground station, not sure how far along that is
3. there are a few places in the cutdown driver that call time.sleep, please replace these with self.thread_sleep

2023-11-03 20:30 UTC, DarylDohner commented on EosPayload/drivers/cutdown_driver.py
> +                raise TypeError("incorrect type")
don't throw, you should instead use logger.error()
also consider a more descriptive message like "incorrect type X, expected CutDown"

2023-11-03 20:30 UTC, DarylDohner commented on EosPayload/drivers/cutdown_driver.py
> +            decoded_msg = CutDown.decode(message)
so clearly this wasnt tested...you need Packet.decode here

2023-11-03 20:30 UTC, DarylDohner commented on EosPayload/drivers/cutdown_driver.py
> +from EosLib.format.formats.cutdown import CutDown
you need to update requirements.txt to the correct EosLib version

2023-11-14 02:35 UTC, VanL15 requested changes
see comments, wait until ping is merged

2023-11-14 02:35 UTC, VanL15 commented on EosPayload/drivers/cutdown_driver.py
> +                user_data['logger'].error(f"incorrect type {packet.data_header.data_type}, expected CutDown")
Make the 'i' in 'incorrect' capital

2023-11-14 02:35 UTC, VanL15 commented on EosPayload/drivers/cutdown_driver.py
> +            user_data['logger'].info(f"received ACK for cutdown from device '{packet.data_header.sender}'"
make the 'r' in 'received' capital

2023-11-14 02:35 UTC, VanL15 commented on EosPayload/drivers/radio_driver.py
> +                    #self.data_log(["LMAO THIS DOESN'T WORK but here is dest: "])#, packet_object.data_header.destination])
Remove this comment

2023-11-14 02:44 UTC, aryanbattula submitted a review, later dismissed
good job!

2023-11-14 02:59 UTC, aryanbattula approved these changes
lgtm

2023-11-14 02:59 UTC, merged