made changes to ping driver
VIP-LES/EosPayload pull request #97
Opened 2023-11-05 19:17 UTC by aryanbattula

refactored ping driver

2023-11-08 23:54 UTC, ianwood103 submitted a review, later dismissed
looks good to me but also didn't test it

2023-11-09 19:39 UTC, VanL15 requested changes

2023-11-09 19:39 UTC, VanL15 commented on EosPayload/drivers/ping_driver.py
> +        packet = Packet(Ping(PingEnum.PING, counter), header)
I think the PingEnum should be ACK and not PING

2023-11-14 01:31 UTC, IonLi09 submitted a review, later dismissed
lgtm

2023-11-14 02:19 UTC, VanL15 requested changes
see comments

2023-11-14 02:19 UTC, VanL15 commented on EosPayload/drivers/ping_driver.py
> +        # raise Exception("Ping driver is temporary disabled until ping format class is implemented")
remove this and the comment above it

2023-11-14 02:19 UTC, VanL15 commented on EosPayload/drivers/ping_driver.py
> +        # packet = Packet(Ping(True, counter), header)
remove this line

2023-11-14 02:19 UTC, VanL15 commented on EosPayload/drivers/radio_driver.py
> +            data_header = packet_object.data_header
remove this line, `data_header` isn't used

2023-11-14 02:19 UTC, VanL15 commented on EosPayload/drivers/radio_driver.py
> +                    self.data_log(["received"])
change this to like "Received packet". Add this above it `# TODO change this to include packet as a string (encode_to_string function) `

2023-11-14 02:19 UTC, VanL15 commented on EosPayload/drivers/radio_driver.py
> +                #     packet = bytes(packet)
remove this comment and the once above it

2023-11-14 02:19 UTC, VanL15 commented on EosPayload/drivers/radio_driver.py
> +                        self.data_log(["sent"])
Change this to "Sent packet". Also add this above it `# TODO change this to include packet as a string (encode_to_string function) `

2023-11-14 02:19 UTC, VanL15 commented on scripts/mqtt_pub_packet.py
> +    # body = bytes(args.body, 'utf8')
remove this line

2023-11-14 02:37 UTC, VanL15 approved these changes
merge :)

2023-11-14 02:38 UTC, merged